name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Construir imagen Docker
        run: docker build -t my-image-name:latest -f Dockerfile .

      - name: Detener contenedor anterior (si existe)
        run: |
          docker stop my-app || true
          docker rm my-app || true

      - name: Ejecutar contenedor nuevo
        run: docker run -d -p 3000:3000 --name my-app my-image-name:latest
